// Generated by Selenium 
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

// Définition du test end-to-end
describe('test E2E', function() {
  this.timeout(30000)
  let driver
  let vars

  // Avant chaque test, initialisation du pilote WebDriver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })

    // Après chaque test, fermeture du pilote WebDriver
  afterEach(async function() {
    await driver.quit();
  })

  // Test principal
  it('test E2E', async function() {
     // Navigation vers l'URL de l'application
    await driver.get("http://localhost:8081/") //mettre la future URL

    // Redimensionnement de la fenêtre du navigateur
    await driver.manage().window().setRect({ width: 1552, height: 832 })

    //actions effectuées lors du test
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(1) > .css-view-175oi2r > .css-textinput-11aywtz")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(1) > .css-view-175oi2r > .css-textinput-11aywtz")).sendKeys("toto@gmail.com")
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .css-view-175oi2r > .css-textinput-11aywtz")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .css-view-175oi2r > .css-textinput-11aywtz")).sendKeys("123456")
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(1) > .r-backgroundColor-14lw9ot > .css-view-175oi2r")).click()
    await driver.findElement(By.css(".r-borderTopColor-1sejfvs > .css-view-175oi2r")).click()
    await driver.findElement(By.css(".r-fontSize-ubezar")).click()
    await driver.findElement(By.css(".r-fontSize-ubezar")).sendKeys("je fais un test end to end")
    await driver.findElement(By.css(".r-color-1j7ouym")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-accessibilityImage-9pa8cd")).click()
    await driver.findElement(By.css(".r-cursor-1loqt21:nth-child(2) > .css-text-146c3p1")).click()
    await driver.findElement(By.css(".r-transitionProperty-1i6wzkk:nth-child(3) > .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-accessibilityImage-9pa8cd")).click()
    {
      const element = await driver.findElement(By.css(".css-accessibilityImage-9pa8cd"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(21) > .css-view-175oi2r")).click()
    await driver.findElement(By.css(".r-fontSize-ubezar")).click()
    await driver.findElement(By.css(".r-fontSize-ubezar")).sendKeys("test end to end pour un groupe de chat")
    await driver.findElement(By.css(".r-color-1j7ouym")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-accessibilityImage-9pa8cd")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(4) > .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(2) > .css-view-175oi2r > .css-view-175oi2r > .css-accessibilityImage-9pa8cd")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) > .css-view-175oi2r > .css-view-175oi2r > .css-view-175oi2r > .css-view-175oi2r > .css-view-175oi2r > .css-view-175oi2r > .css-accessibilityImage-9pa8cd")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(5) > .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-view-175oi2r:nth-child(5) .css-text-146c3p1")).click()
    await driver.findElement(By.css(".r-overflow-1udh08x:nth-child(6) .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-view-175oi2r:nth-child(4) .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-accessibilityImage-9pa8cd")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) > .css-text-146c3p1")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(3) .css-accessibilityImage-9pa8cd")).click()
    await driver.findElement(By.css(".css-view-175oi2r:nth-child(6) > .css-text-146c3p1")).click()
  })
})
