name: testGAaction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test 
      
    - name: SonarQube Scan
      run: |
        docker run \
          --rm \
          -e SONAR_HOST_URL="http://localhost:9000" \
          -e SONAR_LOGIN="sqa_0216dd84fad4a99871204b613193ab6a6b021f17" \
          sonarsource/sonar-scanner-cli:latest

    - name: expo start
      run: npx expo start